# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- powershell: |
<<<<<<< HEAD
    echo "$SEARCHFOR".Splsit(',') | ls -r | % { $_.FullName }
=======
    echo "$Env:SEARCHFOR"
    echo "$Env:SEARCHFOR" | ls -r | % { $_.FullName }
>>>>>>> 3d77e9c292595cfaab892e688e3352f96a75a3b8
  displayName: List Directory Contents
# - script: dotnet build --configuration $(buildConfiguration)
#   displayName: 'dotnet build $(buildConfiguration)'
