# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

resources:
  repositories:
    - repository: build
      type: github
      name: Landorphan/Build
      source: Landorphan/Build
      endpoint: landorphan
  pipelines:
    - pipeline: Landorphan_Build
      project: OSS-Master-Build
      source: landorphan.Build
      trigger:
        branches:
          - master

variables:
  buildConfiguration: 'Release'

trigger:
- master

stages: 
  - template: prepare.yml@build
    # - script: dotnet build --configuration $(buildConfiguration)
    #   displayName: 'dotnet build $(buildConfiguration)'
