# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- powershell: | 
    echo "$Env:SEARCHFOR".Split(',')
    echo "Listing Files"
    $Env:SEARCHFOR.Split(',') | % { ls -r "$_" | % { $_.FullName } }
    echo "END Listing Files"
  displayName: List Directory Contents
# - script: dotnet build --configuration $(buildConfiguration)
#   displayName: 'dotnet build $(buildConfiguration)'
